{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"exception"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nio\/exception"],"traits":[{"interfaceLanguage":"swift"}]}],"relationshipsSections":[{"identifiers":["doc:\/\/org.swift.docc\/s8SendableP"],"kind":"relationships","title":"Conforms To","type":"conformsTo"}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception","interfaceLanguage":"swift"},"topicSections":[{"title":"Initializers","identifiers":["doc:\/\/org.swift.docc\/documentation\/NIO\/exception\/init()","doc:\/\/org.swift.docc\/documentation\/NIO\/exception\/init(type:name:arg1:arg2:retval:)"]},{"title":"Instance Properties","identifiers":["doc:\/\/org.swift.docc\/documentation\/NIO\/exception\/arg1","doc:\/\/org.swift.docc\/documentation\/NIO\/exception\/arg2","doc:\/\/org.swift.docc\/documentation\/NIO\/exception\/name","doc:\/\/org.swift.docc\/documentation\/NIO\/exception\/retval","doc:\/\/org.swift.docc\/documentation\/NIO\/exception\/type"]}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"exception"}],"title":"exception","roleHeading":"Structure","role":"symbol","symbolKind":"struct","externalID":"c:@S@exception","modules":[{"name":"NIO"}],"navigatorTitle":[{"kind":"identifier","text":"exception"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/NIO"]]},"references":{"doc://org.swift.docc/documentation/NIO/exception/arg1":{"role":"symbol","title":"arg1","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"arg1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception\/arg1","kind":"symbol","type":"topic","url":"\/documentation\/nio\/exception\/arg1"},"doc://org.swift.docc/documentation/NIO/exception/init(type:name:arg1:arg2:retval:)":{"role":"symbol","title":"init(type:name:arg1:arg2:retval:)","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"("},{"kind":"externalParam","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"},{"kind":"text","text":", "},{"kind":"externalParam","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">!, "},{"kind":"externalParam","text":"arg1"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"arg2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":", "},{"kind":"externalParam","text":"retval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"},{"kind":"text","text":")"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception\/init(type:name:arg1:arg2:retval:)","kind":"symbol","type":"topic","url":"\/documentation\/nio\/exception\/init(type:name:arg1:arg2:retval:)"},"doc://org.swift.docc/s8SendableP":{"type":"unresolvable","title":"Swift.Sendable","identifier":"doc:\/\/org.swift.docc\/s8SendableP"},"doc://org.swift.docc/documentation/NIO/exception/arg2":{"role":"symbol","title":"arg2","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"arg2"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception\/arg2","kind":"symbol","type":"topic","url":"\/documentation\/nio\/exception\/arg2"},"doc://org.swift.docc/documentation/NIO/exception/type":{"role":"symbol","title":"type","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"type"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Int32","preciseIdentifier":"s:s5Int32V"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception\/type","kind":"symbol","type":"topic","url":"\/documentation\/nio\/exception\/type"},"doc://org.swift.docc/documentation/NIO/exception/init()":{"role":"symbol","title":"init()","fragments":[{"kind":"identifier","text":"init"},{"kind":"text","text":"()"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception\/init()","kind":"symbol","type":"topic","url":"\/documentation\/nio\/exception\/init()"},"doc://org.swift.docc/documentation/NIO/exception/name":{"role":"symbol","title":"name","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"name"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"UnsafeMutablePointer","preciseIdentifier":"s:Sp"},{"kind":"text","text":"<"},{"kind":"typeIdentifier","text":"CChar","preciseIdentifier":"s:s5CChara"},{"kind":"text","text":">!"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception\/name","kind":"symbol","type":"topic","url":"\/documentation\/nio\/exception\/name"},"doc://org.swift.docc/documentation/NIO":{"role":"collection","title":"NIO","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO","kind":"symbol","type":"topic","url":"\/documentation\/nio"},"doc://org.swift.docc/documentation/NIO/exception":{"role":"symbol","title":"exception","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"exception"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"exception"}],"url":"\/documentation\/nio\/exception"},"doc://org.swift.docc/documentation/NIO/exception/retval":{"role":"symbol","title":"retval","fragments":[{"kind":"keyword","text":"var"},{"kind":"text","text":" "},{"kind":"identifier","text":"retval"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Double","preciseIdentifier":"s:Sd"}],"abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/exception\/retval","kind":"symbol","type":"topic","url":"\/documentation\/nio\/exception\/retval"}}}