{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fail"},{"kind":"text","text":"("},{"kind":"externalParam","text":"_"},{"kind":"text","text":" "},{"kind":"internalParam","text":"error"},{"kind":"text","text":": "},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"languages":["swift"],"platforms":["macOS"]}]},{"kind":"parameters","parameters":[{"name":"error","content":[{"type":"paragraph","inlineContent":[{"type":"text","text":"The error from the operation."}]}]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nio\/eventlooppromise\/fail(_:)"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/NIO\/EventLoopPromise\/fail(_:)","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"Deliver an error to the associated "},{"type":"codeVoice","code":"EventLoopFuture<Value>"},{"type":"text","text":" object."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fail"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"title":"fail(_:)","roleHeading":"Instance Method","role":"symbol","symbolKind":"method","externalID":"s:3NIO16EventLoopPromiseV4failyys5Error_pF","modules":[{"name":"NIO"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/NIO","doc:\/\/org.swift.docc\/documentation\/NIO\/EventLoopPromise"]]},"references":{"doc://org.swift.docc/documentation/NIO/EventLoopPromise":{"role":"symbol","title":"EventLoopPromise","fragments":[{"kind":"keyword","text":"struct"},{"kind":"text","text":" "},{"kind":"identifier","text":"EventLoopPromise"}],"abstract":[{"type":"text","text":"A promise to provide a result later."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/EventLoopPromise","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"EventLoopPromise"}],"url":"\/documentation\/nio\/eventlooppromise"},"doc://org.swift.docc/documentation/NIO":{"role":"collection","title":"NIO","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO","kind":"symbol","type":"topic","url":"\/documentation\/nio"},"doc://org.swift.docc/documentation/NIO/EventLoopPromise/fail(_:)":{"role":"symbol","title":"fail(_:)","fragments":[{"kind":"keyword","text":"func"},{"kind":"text","text":" "},{"kind":"identifier","text":"fail"},{"kind":"text","text":"("},{"kind":"typeIdentifier","text":"Error","preciseIdentifier":"s:s5ErrorP"},{"kind":"text","text":")"}],"abstract":[{"type":"text","text":"Deliver an error to the associated "},{"type":"codeVoice","code":"EventLoopFuture<Value>"},{"type":"text","text":" object."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/EventLoopPromise\/fail(_:)","kind":"symbol","type":"topic","url":"\/documentation\/nio\/eventlooppromise\/fail(_:)"}}}