{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"exceptionProtected"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nio\/macherrorcode\/exceptionprotected"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/exceptionProtected","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"An attempt was made to fetch an exception port that is"},{"type":"text","text":" "},{"type":"text","text":"protected, or to abort a thread while processing a protected"},{"type":"text","text":" "},{"type":"text","text":"exception."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"exceptionProtected"}],"title":"MachErrorCode.exceptionProtected","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@Darwin@E@MachErrorCode@MachErrorCodeExceptionProtected","modules":[{"name":"NIO"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/NIO","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode"]]},"references":{"doc://org.swift.docc/documentation/NIO/MachErrorCode/exceptionProtected":{"role":"symbol","title":"MachErrorCode.exceptionProtected","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"exceptionProtected"}],"abstract":[{"type":"text","text":"An attempt was made to fetch an exception port that is"},{"type":"text","text":" "},{"type":"text","text":"protected, or to abort a thread while processing a protected"},{"type":"text","text":" "},{"type":"text","text":"exception."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/exceptionProtected","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/exceptionprotected"},"doc://org.swift.docc/documentation/NIO/MachErrorCode":{"role":"symbol","title":"MachErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachErrorCode"}],"abstract":[{"type":"text","text":"Enumeration describing Mach error codes."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MachErrorCode"}],"url":"\/documentation\/nio\/macherrorcode"},"doc://org.swift.docc/documentation/NIO":{"role":"collection","title":"NIO","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO","kind":"symbol","type":"topic","url":"\/documentation\/nio"}}}