{"primaryContentSections":[{"kind":"declarations","declarations":[{"tokens":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"}],"languages":["swift"],"platforms":["macOS"]}]}],"schemaVersion":{"major":0,"minor":3,"patch":0},"sections":[],"variants":[{"paths":["\/documentation\/nio\/macherrorcode\/failure"],"traits":[{"interfaceLanguage":"swift"}]}],"identifier":{"url":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/failure","interfaceLanguage":"swift"},"abstract":[{"type":"text","text":"The function could not be performed.  A catch-all."}],"kind":"symbol","metadata":{"fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"}],"title":"MachErrorCode.failure","roleHeading":"Case","role":"symbol","symbolKind":"case","externalID":"c:@M@Darwin@E@MachErrorCode@MachErrorCodeFailure","modules":[{"name":"NIO"}]},"hierarchy":{"paths":[["doc:\/\/org.swift.docc\/documentation\/NIO","doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode"]]},"references":{"doc://org.swift.docc/documentation/NIO":{"role":"collection","title":"NIO","abstract":[],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO","kind":"symbol","type":"topic","url":"\/documentation\/nio"},"doc://org.swift.docc/documentation/NIO/MachErrorCode":{"role":"symbol","title":"MachErrorCode","fragments":[{"kind":"keyword","text":"enum"},{"kind":"text","text":" "},{"kind":"identifier","text":"MachErrorCode"}],"abstract":[{"type":"text","text":"Enumeration describing Mach error codes."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode","kind":"symbol","type":"topic","navigatorTitle":[{"kind":"identifier","text":"MachErrorCode"}],"url":"\/documentation\/nio\/macherrorcode"},"doc://org.swift.docc/documentation/NIO/MachErrorCode/failure":{"role":"symbol","title":"MachErrorCode.failure","fragments":[{"kind":"keyword","text":"case"},{"kind":"text","text":" "},{"kind":"identifier","text":"failure"}],"abstract":[{"type":"text","text":"The function could not be performed.  A catch-all."}],"identifier":"doc:\/\/org.swift.docc\/documentation\/NIO\/MachErrorCode\/failure","kind":"symbol","type":"topic","url":"\/documentation\/nio\/macherrorcode\/failure"}}}